// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJXkqcQx9YOrTsOLRhyo4BPzR5sjn5J98',
    appId: '1:794355932926:web:951e76d6225281e2d2cfaf',
    messagingSenderId: '794355932926',
    projectId: 'filmboxd-b35eb',
    authDomain: 'filmboxd-b35eb.firebaseapp.com',
    storageBucket: 'filmboxd-b35eb.appspot.com',
    measurementId: 'G-MFE6R1415T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr1nKAa6Cle8BOfCrYOdIaktTH3dle-4M',
    appId: '1:794355932926:android:19faffb42694890ad2cfaf',
    messagingSenderId: '794355932926',
    projectId: 'filmboxd-b35eb',
    storageBucket: 'filmboxd-b35eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpA7ViQREdCKa6sgdwkwEISoFkf-fFuk',
    appId: '1:794355932926:ios:0bdd0000b72b9288d2cfaf',
    messagingSenderId: '794355932926',
    projectId: 'filmboxd-b35eb',
    storageBucket: 'filmboxd-b35eb.appspot.com',
    iosClientId: '794355932926-ec1jtg76luo3vo201v4n2neqcmkgrmmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.seriesAndTv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbpA7ViQREdCKa6sgdwkwEISoFkf-fFuk',
    appId: '1:794355932926:ios:58f1d18c9afa0ee5d2cfaf',
    messagingSenderId: '794355932926',
    projectId: 'filmboxd-b35eb',
    storageBucket: 'filmboxd-b35eb.appspot.com',
    iosClientId: '794355932926-gj1rtjqg4qlctkqjh3lkbpqubk4r8gdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.seriesAndTv.RunnerTests',
  );
}
